apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-org
spec:
  replicas: 5
  selector:
    matchLabels:
      app: abc-org
  template:
    metadata:
      labels:
        app: abc-org
    spec:
      containers:
      - name: abc-org
        image: siddharth2688/cicd_pipeline:image-1.0
        ports:
          - name: http
            containerPort: 8080
        command:
          - "/bin/sh"
          - "-c"
          - "sh /usr/local/tomcat/bin/startup.sh; while true; do echo hello; sleep 10; done"

---
apiVersion: v1
kind: Service
metadata:
  name: abc-org-app-service
  labels:
    app: abc-org
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31825
  selector:
    app: abc-org
